// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain


struct Circle
{
    float3 position;
    float radius;
};

float time;

RWTexture2D<float4> Result;
float resolutionX;
float resolutionY;
StructuredBuffer<Circle> segments;
float numSegments;
StructuredBuffer<Circle> apples;
float numApples;
float minX;
float maxX;
float minY;
float maxY;
float softness;

float4 lineStart;
float4 lineEnd;

float rand2to1(float2 uv) {
    return frac(sin(dot(uv, float2(12.9898, 78.233))) * 43758.5453);
}

float2 rand2to2(float2 uv) {
    return float2(frac(cos(dot(uv, float2(12.9898, 78.233) + uv.x)) * 73418.5353), frac(cos(dot(uv * uv.y, float2(15.9898, -78.233))) * 14185.5452));
}

float gnoise(float2 n) {
	const float2 d = float2(0.0, 1.0);
    float2  b = floor(n), 
    f = smoothstep(d.xx, d.yy, frac(n));

    //float2 f = frac(n);
	//f = f*f*(3.0-2.0*f);

    float x = lerp(rand2to1(b), rand2to1(b + d.yx), f.x),
    y = lerp(rand2to1(b + d.xy), rand2to1(b + d.yy), f.x);

	return lerp( x, y, f.y );
}

float CurvePong(float f) {
    bool temp = floor(f / 2) % 2 == 1;
    if (floor(f) % 2 == 1) {
        f *= -1;
    }
    float o = pow(frac(f), 3);
    if (temp) {
        o *= -1;
    }
    return o / 2 + 0.5;
}

float Voronoi(float2 uv) {
    float2 baseCell = floor(uv);

    float minDistToCell = 10;
    [unroll]
    for(int x=-2; x<=2; x++){
        [unroll]
        for(int y=-2; y<=2; y++){
            float2 cell = baseCell + float2(x, y);
            float2 cellPosition = cell + rand2to2(cell) + float2(gnoise(cell + sin(cell) * time / 3), gnoise(2 * cell + sin(cell) * time / 3));
            float2 toCell = cellPosition - uv;
            float distToCell = length(toCell);
            if(distToCell < minDistToCell){
                minDistToCell = distToCell;
            }
        }
    }
    return minDistToCell;
}

float4 WaterShader(float2 uv) {
    float4 v = float4(Voronoi(uv / 30 + time/3 + float2(sin(time * 3), cos(time)) / 30).xxx, 1);
    v = log(exp(3 * v) + exp(3 * 0.1)) / 3;
    v += float4(0, 0.25, 0.21, 0);
    float4 t = v;
    v = pow(v, 3);
    float4 i = 1 - v;
    v += i * float4(0, 0.6, 0.6, 1);
    v = 0.3 * t + 0.4 * v;
    return v;
}

float4 WallpaperColor(float2 uv) {
    uv *= float2(resolutionX / resolutionY, 1) * 480;
    return WaterShader(uv) * 0.7 + WaterShader(uv / 0.9 + 14013.13519) * 0.35;
}

float4 BackgroundColor(float2 id, float2 uv, float3 wp) {
    if (length(Result[id.xy] - float4(1,1,1,1)) > 0.8) {
        if (wp.x < minX || wp.x > maxX || wp.y < minY || wp.y > maxY) return WallpaperColor(uv) * 0.1;
        return WallpaperColor(uv);
    }
    return Result[id.xy];
}

float4 AntiAlias(float4 mainColor, float4 background, float distance, float sharpness) {

    return lerp(mainColor, background, saturate(distance * sharpness)).xyzz;
}

float4 PixelColor(float3 id) {
    float2 uv = float2(id.x / resolutionX, id.y / resolutionY);
    float3 wp = float3(uv.x * (maxX - minX) + minX, uv.y * (maxY - minY) + minY, 0);
    if ((maxX - minX) / resolutionX > (maxY - minY) / resolutionY) {
        wp *= float3(1, (maxX - minX) * resolutionY / (maxY - minY) / resolutionX, 0);
    }
    if ((maxX - minX) / resolutionX < (maxY - minY) / resolutionY) {
        wp *= float3((maxY - minY) * resolutionX / (maxX - minX) / resolutionY, 1, 0);
    }

    float4 totalColor = BackgroundColor(id.xy, uv, wp);

    float expSums = 0;
    for (int i = 0; i < numSegments; i++) {
        float signedDistance = length(wp - segments[i].position) - segments[i].radius / 2.;
        expSums += exp(-softness * signedDistance);
    }
    float snakeSD = log(expSums) / (-softness);
    float4 snakeColor;

    //snakeColor = float4(1, 0, 1, 1);
    //snakeColor = float4(sin(uv.x + time / 2.71828), uv.y, sin(time), 1);
    //snakeColor = float4(abs(frac(uv.x * 3 + time / 12.71828) - 0.5) * 4 - 0.5, uv.y, abs(frac(time / 10) - 0.5) * 4 - 0.5, 1);
    snakeColor = float4(CurvePong(uv.x * 10 + time / 2.7828), uv.y, abs(frac(time / 10) - 0.5) * 4 - 0.5, 1);

    totalColor = AntiAlias(snakeColor, totalColor, snakeSD, 40);

    for (int j = 0; j < numApples; j++) {
        float appleSD = length(wp - apples[j].position) - apples[j].radius;
        totalColor = AntiAlias(float4(1, 0, 0, 1), totalColor, appleSD, 20);
    }

    const float lineMinWidth = 0.01;
    const float lineWidth = 0.05;
    const float lineSharpness = 33;

    bool inLine = wp.x >= min(lineStart.x, lineEnd.x) && wp.x <= max(lineStart.x, lineEnd.x) && wp.y >= min(lineStart.y, lineEnd.y) && wp.y <= max(lineStart.y, lineEnd.y);
    if (abs(lineEnd.y - lineStart.y) < lineWidth && abs(lineStart.y - wp.y) < lineWidth && wp.x >= min(lineStart.x, lineEnd.x) && wp.x <= max(lineStart.x, lineEnd.x)) {
        totalColor = AntiAlias(float4(0, 0, 0, 1), totalColor, abs(lineStart.y - wp.y) - lineMinWidth, lineSharpness);
    }
    if (abs(lineEnd.x - lineStart.x) < lineWidth && abs(lineStart.x - wp.x) < lineWidth && wp.y >= min(lineStart.y, lineEnd.y) && wp.y <= max(lineStart.y, lineEnd.y)) {
        totalColor = AntiAlias(float4(0, 0, 0, 1), totalColor, abs(lineStart.x - wp.x) - lineMinWidth, lineSharpness);
    }
    if (inLine) {
        if (abs((lineEnd.y - lineStart.y) / (lineEnd.x - lineStart.x)) > 1) {
            if (abs((lineEnd.x - lineStart.x) / (lineEnd.y - lineStart.y) * (wp.y - lineStart.y) + lineStart.x - wp.x) < lineWidth) {
                totalColor = AntiAlias(float4(0, 0, 0, 1), totalColor, abs((lineEnd.x - lineStart.x) / (lineEnd.y - lineStart.y) * (wp.y - lineStart.y) + lineStart.x - wp.x) - lineMinWidth, lineSharpness);
            }
        }
        else {
            if (abs((lineEnd.y - lineStart.y) / (lineEnd.x - lineStart.x) * (wp.x - lineStart.x) + lineStart.y - wp.y) < lineWidth) {
                totalColor = AntiAlias(float4(0, 0, 0, 1), totalColor, abs((lineEnd.y - lineStart.y) / (lineEnd.x - lineStart.x) * (wp.x - lineStart.x) + lineStart.y - wp.y) - lineMinWidth, lineSharpness);
            }
        }
    }

    return totalColor;
}

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    Result[id.xy] = PixelColor(id);
}